version: "3.9"
services:
  mongo:
    image: mongo:4.4.6
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=snuttadmin
      - MONGO_INITDB_ROOT_PASSWORD=snuttpw
  redis:
    image: redis:6.2.1
    ports:
      - 6379:6379
